### ISSUE TITLE
Error: No such file or directory: 'styles.csv'

### ISSUE THREAD

**Issue by yi** [chrisgoringe/Styles-Editor#1]
Step to reproduce:
1. clone this repo to `stable-diffusion/stable-diffusion-webui/extensions`
2. launch a1111 stable diffusion webui

python throw this error: Error: No such file or directory: 'styles.csv'
stable-diffusion/stable-diffusion-webui/extensions/Styles-Editor/scripts/main.py", line 47, in on_ui_tabs
    cls.dataeditor = gr.Dataframe(value=cls.load_styles, label="Styles",

**Comment by chrisgoringe** [comment]
Have you previously saved a style (in the txt2img or img2img tab)? If not, could you do so, and then try again?

**Comment by chrisgoringe** [comment]
Fixed in latest build
