### ISSUE TITLE
unable to locate the "Style Editor" tab

### ISSUE THREAD

**Issue by navimixu** [chrisgoringe/Styles-Editor#19]
installed and loaded the extension but i was unable to find the that mentioned "Style Editor" tab.

**Comment by chrisgoringe** [comment]
Could you confirm that you did "Apply and restart UI" after loading?

This is what my tab bar looks like on a clean install of A1111, after loading the extension and restarting the UI:

![image](https://github.com/chrisgoringe/Styles-Editor/assets/4371971/cd158e17-2a29-45e6-bb61-6464217b47b1)

`Style Editor` is between `Train` and `Settings` for me.

If it's not there, please add more details (how you installed, log files, anything like that)

**Comment by chrisgoringe** [comment]
Please post a screenshot of the very bottom of the window - this section:
![image](https://github.com/chrisgoringe/Styles-Editor/assets/4371971/3ee5a4eb-ec31-49b7-b6ef-8fcf9dc805f2)
Most likely cause is that your Automatic1111 is a bit old. In which case see fix in #20 

I will close this if no further information is added.
