### ISSUE TITLE
Re-order rows

### ISSUE THREAD

**Issue by theallyprompts** [chrisgoringe/Styles-Editor#2]
Hi! Great extension, really useful! 

Would it be possible to implement row re-ordering? Or the ability to insert a new row in between a particular row number?

**Comment by chrisgoringe** [comment]
Great timing on that request - it was right at the top of my to-do list! 

Latest commit has a (fairly primitive, experimental) version of this. An index column is automatically added (and recreated whenever you save or load). Change the values in that column, then sort by that column; when you save the display order will be the save order (and the index column re-created to reflect the order). Note that you aren't constrained to integer values (so use 1.5 to go between 1 and 2...).

Probably makes more sense hands-on than me describing it. Let me know if it works for you, and feel free to suggest changes,
