### ISSUE TITLE
The extension is reading the style.csv file with incorrect delimiters, the first delimiter is not the name but the number instead?

### ISSUE THREAD

**Issue by xhoxye** [chrisgoringe/Styles-Editor#22]
The extension is reading the style.csv file with incorrect delimiters, the first delimiter is not the name but the number instead?
![301](https://github.com/chrisgoringe/Styles-Editor/assets/129571231/e142a4d3-1f60-4c3a-ad52-3106b5741afb)
![302](https://github.com/chrisgoringe/Styles-Editor/assets/129571231/52c44ba8-d9ba-4dde-8292-1c2bc0087e32)

**Comment by chrisgoringe** [comment]
What's the actual problem here? 

The extension adds a column on the left for sorting, but your positive and negative prompts are all in the right place?

**Comment by xhoxye** [comment]
positive and negative prompts are all in the right place,can be filled in correctly,But the extension does not read correctly,

**Comment by xhoxye** [comment]
So if I use this extension to edit, it will save with incorrect delimiters?

**Comment by xhoxye** [comment]
This is the original format delimiter.
![001](https://github.com/chrisgoringe/Styles-Editor/assets/129571231/7476d6e1-ad26-42c9-b989-db61e59e34b8)
![002](https://github.com/chrisgoringe/Styles-Editor/assets/129571231/6f867e5f-c7c0-4921-94f6-42d40729d7f2)

**Comment by chrisgoringe** [comment]
Could you post the styles file here so I can test it please.

**Comment by xhoxye** [comment]
[styles.csv](https://github.com/chrisgoringe/Styles-Editor/files/11713880/styles.csv)

**Comment by chrisgoringe** [comment]
OK, that style file has some weird lines in it (lines 2 and 6 have extra commas in them).
I've made the extension more robust in the latest commit, should work now.
