### ISSUE TITLE
Lost Entries

### ISSUE THREAD

**Issue by Tikishark777** [chrisgoringe/Styles-Editor#27]
Everything worked well initially.  I was able to create three entries and then pull them up using the styles drop-down menu paired with the apply styles button.  However, when I created a new prompt in the Txt2img prompt area and then saved it the traditional way (without using the Styler Editor) I lost everything.  I've not been able to figure out a way to recover what's already been entered.  The drop-down menu on the Txt2img tab still displays my three entries, but they won't load.  The Style Editor is now completely blank.  Refreshing does nothing.

<img width="257" alt="image" src="https://github.com/chrisgoringe/Styles-Editor/assets/136287741/c25ca997-ec6e-43a7-b9ad-02b3b4555037">

<img width="891" alt="image" src="https://github.com/chrisgoringe/Styles-Editor/assets/136287741/52e21be7-a43c-457d-a6e8-f17e4a1a83af">

**Comment by Tikishark777** [comment]
I was able to restore my database by finding the styles.csv.bak and replacing the styles.csv fiile in the stable-diffusion-webui directory.  However, it does appear there's a flaw in the code if someone tries to save a style the traditional way.  Not sure if I did something wrong, but that may be a caution you could post if that is something that still needs fixing.

**Comment by chrisgoringe** [comment]
Thanks - I'll look at this as a matter of priority. Any additional information would be a big help, since what you described definitely shouldn't happen!

Working on a better backup/restore as an extra fail safe...

**Comment by Tikishark777** [comment]
Sorry, I wasn't able to provide more detail, but it looks like you've updated the file.  Thank you for your hard work.
