### ISSUE TITLE
Multiple Style files

### ISSUE THREAD

**Issue by theallyprompts** [chrisgoringe/Styles-Editor#3]
Hear me out! I know WebUI looks for a single "Style.csv" - but would there be any way to implement multiple files which could be swapped between; a file for style rows, a file for favorite prompts, etc. 

There might be a better way - but since it's just working with .csv files, could the system perhaps just copy/write the values from the selected file into Style.csv? So WebUI would always be looking at Style.csv, but depending on which file we select in the UI it has different values loaded into it? Unless there is a way to force WebUI to look at a different location/name for the Style.csv, of course.

Does that make sense? Thanks!

**Comment by chrisgoringe** [comment]
I can think of a couple of ways of doing something like that.

One would be a style file selector (a drop-down menu to allow you to swap between different style files). That could almost be a separate extension (and fairly simple to add).

The main question would be whether you want to be able to combine styles from different files (eg a favourite prompt from one, and a style from another) when generating an image. 

In that case we'd need a different approach - some way of subdividing the style file. 

Even now you could do that using the notes column and the filter (maybe put #prompt in the notes then filter).

Thoughts?

**Comment by theallyprompts** [comment]
Ah, I envisioned a Style file selector; first option. 

However, now you mention combining records from different files, if option 1 was in place, couldn't you load up Style1.csv and send row 1 to the positive prompt (or negative, depending on content), then switch to Style2.csv and append row N to the prompt. Pretty much how it works now, but pulling rows from different files.

**Comment by chrisgoringe** [comment]
Problem is, that would involve messing with the way the styles are loaded by the other components/scripts, which makes for much greater complexity and risk of incompatible stuff.

Perhaps a solution would be to have multiple files in the extension, but it merges them all into a single file for the rest of the UI. Maybe with a prefix to identify the file each is from.

**Comment by chrisgoringe** [comment]
(Hey - are you theally from https://civitai.com/user/theally/models? Strange co-incidence, I was just downloading the CN1.1 models and noticed the name...)

**Comment by theallyprompts** [comment]
> (Hey - are you theally from https://civitai.com/user/theally/models? Strange co-incidence, I was just downloading the CN1.1 models and noticed the name...)

Yes, that's me! I have written a tutorial on this extension for my Patrons - it's super useful!

**Comment by chrisgoringe** [comment]
So I've implemented this on a branch, as there are some consequential changes (main one being that we now autosave changes as you go along instead of having a save button).

Take a look at branch [3-multiples-styles](https://github.com/chrisgoringe/Styles-Editor/tree/3-multiples-styles), and see if it makes sense and does what you were thinking...

**Comment by theallyprompts** [comment]
I'll test asap! Exciting!

**Comment by chrisgoringe** [comment]
Great. btw, I'd love to see your guide on using this - it would help me to get a sense of how it looks and feels from a user perspective.

**Comment by theallyprompts** [comment]
Love the multi-style implementation, works really well, and is quite straightforward. Extremely useful. 

If you're on Discord, drop me a message (TheAlly#7211) and I'll send you the guide, as it stands right now. It's Patron only content, so I'd rather not share the link here.

**Comment by chrisgoringe** [comment]
Done

**Comment by chrisgoringe** [comment]
> TheAlly#7211

Sent you a friend request on Discord (trevik#8341)
