### ISSUE TITLE
unable to locate the "Style Editor" tab

### ISSUE THREAD

**Issue by flare777** [chrisgoringe/Styles-Editor#36]
hello,
I was getting the same error as #20, 
I referred to the article and updated the gradio version to his 3.23.0 but still the same error.
Is it a problem with another module?

![image](https://github.com/chrisgoringe/Styles-Editor/assets/21178795/e1ff6af1-efce-4423-b6a7-43c650d37e22)

[styles.csv](https://github.com/chrisgoringe/Styles-Editor/files/11724055/styles.csv)

**Comment by chrisgoringe** [comment]
Installer now checks for gradio version

**Comment by flare777** [comment]
I ran an update, but I'm still at version 3.23.0 of gradio.
Attach the execution result.
thank you.

[Execution result.txt](https://github.com/chrisgoringe/Styles-Editor/files/11730817/Execution.result.txt)

**Comment by chrisgoringe** [comment]
The execution results shows you at 3.31.0

**Comment by flare777** [comment]
In SD UI, there is no change.
Attached is the SD execution result.
thank you.

![image](https://github.com/chrisgoringe/Styles-Editor/assets/21178795/a8143359-b2d0-4203-853d-617405fb41a3)
[SD Execution result.txt](https://github.com/chrisgoringe/Styles-Editor/files/11731602/SD.Execution.result.txt)

**Comment by flare777** [comment]
The gradio update was successful.
However, the gradio version displayed in the SD UI is still old.
Is this because the gradio update seems to have succeeded at first glance but actually failed? Or did the update succeed but the version displayed in the UI is still old for some other reason?
I've done some research on my own, but haven't found a solution yet.

thank you.

**Comment by flare777** [comment]
solved.
I solved it by deleting all the SD and doing a clean install.
thank you.
