### ISSUE TITLE
New Update Removes Notes Section

### ISSUE THREAD

**Issue by Tikishark777** [chrisgoringe/Styles-Editor#40]
I wasn't sure if you were aware, but the new update removed the notes section for each entry.  Is this a feature that can be added back or since the main UI of Automatic doesn't have a place for that information is no longer compatible?  Thanks

**Comment by chrisgoringe** [comment]
The notes information was being lost whenever you saved a style through the main ui, so I removed it. I hope to bring it back in another form...

**Comment by Tikishark777** [comment]
Okay, thank you.  I've been using the extension for a few days, and I really like it.  Great work.

**Comment by chrisgoringe** [comment]
Notes are back.

**Comment by Tikishark777** [comment]
Thank you, everything is working great...
