### ISSUE TITLE
Carriage returns in styles?

### ISSUE THREAD

**Issue by dchatel** [chrisgoringe/Styles-Editor#42]
How do you handle carriage returns in styles?

For example, if you have a style like this:
```
token1, token2
token3, token4, token5
token6
```
and you edit the style within your extension, the carriage returns currently get lost. Or maybe I'm doing something wrong?

**Comment by chrisgoringe** [comment]
Hmm. I don't handle them at all. Interesting problem...

**Comment by chrisgoringe** [comment]
Newlines are preserved if a cell isn't edited (but they are displayed simply as spaces in the editor). 
However, if a cell is edited the newlines are simply deleted. Similarly if a cell is copied and pasted, the paste loses the newline (but the cell that was copied from doesn't lose it).

**Comment by chrisgoringe** [comment]
OK, so this is because the gradio dataframe uses an html INPUT tag for editing; and INPUT doesn't allow line breaks. 

The csv file has a linebreak, pandas reads it as \n. So maybe convert all `\` to `\\` on load, and convert back on save...

**Comment by chrisgoringe** [comment]
Latest build uses <br> in the editor to represent line breaks.
