### ISSUE TITLE
Since Latest Commit, no Records

### ISSUE THREAD

**Issue by theallyprompts** [chrisgoringe/Styles-Editor#5]
Hey! Unfortunately, the extension is no longer loading my Style.csv, or allowing me to add new records. The table is blank, and the buttons inoperable.

Also, when I mouse over the "Exact Match" in below the filter, the cursor changes to a red "denied" circle - I can no longer drop-down the list to select a different filter method.

**Comment by chrisgoringe** [comment]
That's not good. I've reverted the last couple of updates, please let me know if it works now.

**Comment by chrisgoringe** [comment]
mechanism for getting the setting for the location of the style file differs between Automatc1111 and Vladmandic. Merged a fix that works for both.
