### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by nikgrid7** [chrisgoringe/Styles-Editor#62]
Hi Chris. Sorry I feel like kind of a dumbass, where do I go in A1111 to use this?
It's definitely installed and I can apply styles to my prompts but I cant edit those styles in A1111

thanks for helping a dumbass out :)

**Comment by chrisgoringe** [comment]
If you have installed the extension, you should see a tab labelled "Style Editor" in your A1111 window - something like this one:
![image](https://github.com/chrisgoringe/Styles-Editor/assets/4371971/952d88ea-5057-40d7-a3dd-741caa3fd128)
If your tab bar doesn't have "Style Editor" in it then either you didn't manage to install properly for some reason, or it is failing to launch. In either case, it's a bug and I'll see if I can help!

**Comment by bobpuffer1** [comment]
It didn't show up for me either. I'm getting the following error in Terminal:

Error executing callback ui_tabs_callback for /Users/bobpuffer/stable-diffusion-webui/extensions/Styles-Editor/scripts/main.py
Traceback (most recent call last):
  File "/Users/bobpuffer/stable-diffusion-webui/modules/script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/bobpuffer/stable-diffusion-webui/extensions/Styles-Editor/scripts/main.py", line 252, in on_ui_tabs
    cls.dataeditor.input(fn=cls.handle_dataeditor_input, inputs=[cls.dataeditor, cls.autosort_checkbox], outputs=cls.dataeditor)
AttributeError: 'Dataframe' object has no attribute 'input'

**Comment by chrisgoringe** [comment]
See #20 - this extension requires gradio 3.30. If you update to the latest version of A1111 (which uses 3.31) it should work. Alternatively, update manually by typing this at the command line in your A1111 directory:

```
venv/Scripts/activate.bat
pip install gradio==3.31.0 --upgrade
```

If that doesn't fix it, feel free to reopen this issues.

**Comment by bobpuffer1** [comment]
The latest release of automatic 11:11 contains a lot of errors for extensions. It blows a lot of extensions out of the water so that's not gonna happen the activate script, which happens to be in the bin directory on a Mac. I don't know about the PC but the first two lines say it should not be run directly that it should be run with a helper file so I'm pretty skeptical about upgrading Gradio that way thanks

**Comment by chrisgoringe** [comment]
A1111 has been running gradio 3.31 since May 19th.
