### ISSUE TITLE
Error on the install of styles editor after upgrading to newer Gradio

### ISSUE THREAD

**Issue by bobpuffer1** [chrisgoringe/Styles-Editor#63]
I get this error after upgrading:

Error executing callback ui_tabs_callback for /Users/bobpuffer/stable-diffusion-webui/extensions/Styles-Editor/scripts/main.py
Traceback (most recent call last):
  File "/Users/bobpuffer/stable-diffusion-webui/modules/script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/bobpuffer/stable-diffusion-webui/extensions/Styles-Editor/scripts/main.py", line 252, in on_ui_tabs
    cls.dataeditor.input(fn=cls.handle_dataeditor_input, inputs=[cls.dataeditor, cls.autosort_checkbox], outputs=cls.dataeditor)
AttributeError: 'Dataframe' object has no attribute 'input'

**Comment by bobpuffer1** [comment]
I uninstalled and reinstalled and restarted everything and still get the same error.

**Comment by chrisgoringe** [comment]
Can you confirm what version of gradio you have? The specific error message suggests that it's 3.29 or below.

**Comment by bobpuffer1** [comment]
You're right. Current version is three point .29. I don't know what happened but I'll check into it and get back to you. Thanks sorry about that

**Comment by chrisgoringe** [comment]
No problem. I'll close this, but feel free to open another issue if you still have problems.

**Comment by bobpuffer1** [comment]
Just a point of information I reset my commit to June 1 for 131 and that upgraded Gradio so then your extension showed up. I'll let you know if I have any problems. I think you should have a discussion tab in your GitHub since you don't want to have issues created for every communication.
