### ISSUE TITLE
[BUG]: AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by robonxt** [chrisgoringe/Styles-Editor#85]
On the latest commit (71655f0), I'm getting errors in the terminal regarding your extension with the error `AttributeError: 'DataFrame' object has no attribute 'append'`

According to [this Slack Overflow post](https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append), the command `append` was removed after being deprecated.

Otherwise, the extension is loading my saves ok so far, although I have not tested out changing or adding new rows yet.

**Comment by chrisgoringe** [comment]
Should be fixed if you update.

**Comment by robonxt** [comment]
So far so good! I did the steps again as I did to trigger the console errors, and no errors so far. Thank you for the fast fix!
